# Домашнее задание HW01: Основы NumPy

В этом ноутбуке демонстрируются базовые операции с библиотекой NumPy:
- создание массивов
- атрибуты массивов
- индексирование и срезы
- векторные операции и статистики


## 1. Импорт библиотеки NumPy


In [ ]:
# Импортируем NumPy с общепринятым сокращением np
import numpy as np

print(f"NumPy version: {np.__version__}")


NumPy version: 2.3.5


## 2. Создание массивов

### 2.1 Создание массива из списка Python


In [ ]:
# Создание одномерного массива из списка
python_list = [1, 2, 3, 4, 5]
arr_from_list = np.array(python_list)
print("Одномерный массив из списка:")
print(arr_from_list)

# Создание двумерного массива из вложенного списка
nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arr_2d = np.array(nested_list)
print("\nДвумерный массив (матрица):")
print(arr_2d)


Одномерный массив из списка:
[1 2 3 4 5]

Двумерный массив (матрица):
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 2.2 Создание массивов с помощью функций NumPy


In [ ]:
# Массив из нулей
zeros_arr = np.zeros((3, 4))  # матрица 3x4
print("Массив из нулей (3x4):")
print(zeros_arr)

# Массив из единиц
ones_arr = np.ones((2, 3))
print("\nМассив из единиц (2x3):")
print(ones_arr)

# Массив с последовательностью чисел (аналог range)
arange_arr = np.arange(0, 10, 2)  # от 0 до 10 с шагом 2
print("\nМассив arange (0, 10, 2):")
print(arange_arr)

# Массив с равномерно распределёнными значениями
linspace_arr = np.linspace(0, 1, 5)  # 5 чисел от 0 до 1
print("\nМассив linspace (0, 1, 5):")
print(linspace_arr)

# Единичная матрица
eye_arr = np.eye(3)  # единичная матрица 3x3
print("\nЕдиничная матрица 3x3:")
print(eye_arr)


Массив из нулей (3x4):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Массив из единиц (2x3):
[[1. 1. 1.]
 [1. 1. 1.]]

Массив arange (0, 10, 2):
[0 2 4 6 8]

Массив linspace (0, 1, 5):
[0.   0.25 0.5  0.75 1.  ]

Единичная матрица 3x3:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 3. Атрибуты массивов (shape, dtype)


In [ ]:
# Демонстрация атрибутов на примере двумерного массива
sample_arr = np.array([[1.5, 2.0, 3.5], [4.0, 5.5, 6.0]])

print("Исходный массив:")
print(sample_arr)
print()

# shape - форма массива (размеры по каждой оси)
print(f"Форма (shape): {sample_arr.shape}")

# dtype - тип данных элементов
print(f"Тип данных (dtype): {sample_arr.dtype}")

# ndim - количество измерений
print(f"Количество измерений (ndim): {sample_arr.ndim}")

# size - общее количество элементов
print(f"Количество элементов (size): {sample_arr.size}")


Исходный массив:
[[1.5 2.  3.5]
 [4.  5.5 6. ]]

Форма (shape): (2, 3)
Тип данных (dtype): float64
Количество измерений (ndim): 2
Количество элементов (size): 6


## 4. Индексирование и срезы


In [ ]:
# Индексирование одномерного массива
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(f"Исходный массив: {arr}")
print()

# Получение отдельного элемента по индексу
print(f"Элемент с индексом 0: {arr[0]}")
print(f"Элемент с индексом 3: {arr[3]}")
print(f"Последний элемент (индекс -1): {arr[-1]}")
print()

# Срезы (slicing)
print(f"Первые 3 элемента (arr[:3]): {arr[:3]}")
print(f"Элементы с 3 по 7 (arr[3:7]): {arr[3:7]}")
print(f"Каждый второй элемент (arr[::2]): {arr[::2]}")
print(f"Массив в обратном порядке (arr[::-1]): {arr[::-1]}")


Исходный массив: [ 10  20  30  40  50  60  70  80  90 100]

Элемент с индексом 0: 10
Элемент с индексом 3: 40
Последний элемент (индекс -1): 100

Первые 3 элемента (arr[:3]): [10 20 30]
Элементы с 3 по 7 (arr[3:7]): [40 50 60 70]
Каждый второй элемент (arr[::2]): [10 30 50 70 90]
Массив в обратном порядке (arr[::-1]): [100  90  80  70  60  50  40  30  20  10]


In [ ]:
# Индексирование двумерного массива
matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
print("Исходная матрица:")
print(matrix)
print(f"Форма: {matrix.shape}")
print()

# Получение элемента [строка, столбец]
print(f"Элемент [0, 0]: {matrix[0, 0]}")
print(f"Элемент [1, 2]: {matrix[1, 2]}")
print()

# Срезы для двумерного массива
print("Первая строка:")
print(matrix[0, :])

print("\nВторой столбец:")
print(matrix[:, 1])

print("\nПодматрица (первые 2 строки, первые 2 столбца):")
print(matrix[:2, :2])


Исходная матрица:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Форма: (3, 4)

Элемент [0, 0]: 1
Элемент [1, 2]: 7

Первая строка:
[1 2 3 4]

Второй столбец:
[ 2  6 10]

Подматрица (первые 2 строки, первые 2 столбца):
[[1 2]
 [5 6]]


## 5. Векторные операции и статистики


In [ ]:
# Поэлементные операции
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print(f"Массив a: {a}")
print(f"Массив b: {b}")
print()

# Поэлементное сложение
print(f"a + b = {a + b}")

# Поэлементное вычитание
print(f"b - a = {b - a}")

# Поэлементное умножение
print(f"a * b = {a * b}")

# Поэлементное деление
print(f"b / a = {b / a}")

# Операции со скаляром (broadcasting)
print(f"\na * 2 = {a * 2}")
print(f"a ** 2 = {a ** 2}")


Массив a: [1 2 3 4 5]
Массив b: [10 20 30 40 50]

a + b = [11 22 33 44 55]
b - a = [ 9 18 27 36 45]
a * b = [ 10  40  90 160 250]
b / a = [10. 10. 10. 10. 10.]

a * 2 = [ 2  4  6  8 10]
a ** 2 = [ 1  4  9 16 25]


In [ ]:
# Базовые статистики
data = np.array([12, 15, 18, 22, 25, 30, 35, 40, 45, 50])
print(f"Данные: {data}")
print()

# Среднее значение
print(f"Среднее (mean): {np.mean(data)}")

# Медиана
print(f"Медиана (median): {np.median(data)}")

# Стандартное отклонение
print(f"Стандартное отклонение (std): {np.std(data):.2f}")

# Сумма элементов
print(f"Сумма (sum): {np.sum(data)}")

# Минимум и максимум
print(f"Минимум (min): {np.min(data)}")
print(f"Максимум (max): {np.max(data)}")


Данные: [12 15 18 22 25 30 35 40 45 50]

Среднее (mean): 29.2
Медиана (median): 27.5
Стандартное отклонение (std): 12.35
Сумма (sum): 292
Минимум (min): 12
Максимум (max): 50


## Заключение

В этом ноутбуке были рассмотрены основные операции с библиотекой NumPy:

1. **Создание массивов** — из списков и с помощью функций (`zeros`, `ones`, `arange`, `linspace`)
2. **Атрибуты** — `shape`, `dtype`, `ndim`, `size`
3. **Индексирование и срезы** — доступ к элементам и подмассивам
4. **Векторные операции** — поэлементные вычисления
5. **Статистики** — `mean`, `std`, `sum`, `min`, `max`
